version: "3.8"

services:
  hockey-stats:
    build: ./hockey-stats
    container_name: hockey-stats
    restart: unless-stopped
    ports:
      - "1000:8501"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}