version: "3.8"

services:
  homepage:
    build: ./homepage
    container_name: homepage
    restart: unless-stopped
    ports:
      - "80:8501"

  hockey-stats:
    build: ./hockey-stats
    container_name: hockey-stats
    restart: unless-stopped
    ports:
      - "1000:8501"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  livetrail-scrap:
    build: ./livetrail-scrap
    container_name: livetrail-scrap
    restart: unless-stopped
    ports:
      - "1001:8501"

  read-later:
    build: ./read-later
    container_name: read-later
    restart: unless-stopped
    ports:
      - "1003:8501"

  three-js-labs:
    build: ./three-js-labs
    container_name: three-js-labs
    restart: unless-stopped
    ports:
      - "1002:1002"
      - "5173:5173"
    volumes:
      - /home/tom/apps/three-js-labs/scenes:/app/scenes